import mongoose, { Schema, Document } from 'mongoose';
import { ServerSeed } from '../../utils/game_seed';

/**
 * Abstract Base Game Model
 *
 * Defines the core properties shared across all casino games (Mines, Dice, etc.)
 * Intended to be extended by specific game schemas.
 */

export interface IGame extends Document {
  user_id: mongoose.Types.ObjectId;
  wager_amount: number;
  currency_id: mongoose.Types.ObjectId;

  // payout set after the game finishes
  // 0 if the user lost, positive number if the user won
  payout?: number;

  // Client and host seeds for verification
  server_seed: ServerSeed; // generated by server
  client_seed?: string; // provided by player
  game_seed?: string; // set after client_seed is provided

  // mongoose timestamps
  createdAt: Date;
  updatedAt: Date;
}

export const BaseGameSchema = new Schema(
  {
    user_id: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    wager_amount: {
      type: Number,
      required: true,
      min: 0,
    },
    currency_id: {
      type: Schema.Types.ObjectId,
      ref: 'Cryptocurrency',
      required: true,
    },
    payout: {
      type: Number,
      min: 0,
    },
    server_seed: {
      type: {
        seed: String,
        hash: String,
      },
      required: true,
    },
    client_seed: String,
    game_seed: String,
    completed_at: Date,
  },
  {
    timestamps: true,
    discriminatorKey: 'gameType',
  }
);

// Prevent overwriting the model if it already exists (common in Next.js hot reload)
export const Game = mongoose.models.Game || mongoose.model<IGame>('Game', BaseGameSchema);
