import mongoose, { Schema, Document } from 'mongoose';
import { ServerSeed } from '../../utils/game_seed';

/**
 * Mines Game State Model
 * 
 * Represents a single Mines game session.
 * Grid: 5x5 = 25 cells
 * Mines count: configurable (typically 1-24, default 5)
 * Gems: remaining cells after placing mines
 */

export interface IMinesGame extends Document {
  // Player identifier (Nostr public key or user ID)
  player_pubkey: string;

  mines_count: number; // number of bombs on board

  // Game metrics
  current_multiplier: number; // starts at 1.0, increases per gem revealed
  wager_amount: number; // initial bet in sats or currency

  // Game status
  // 'ACTIVE': game in progress, playable
  // 'LOST': hit a bomb, game over
  // 'CASHED_OUT': player called cashout, game over with winnings
  // 'WAITING_CLIENT_SEED': game session created but no client seed yet
  // 'CANCELED': game canceled before starting (e.g. expired without client seed)
  status: 'WAITING_CLIENT_SEED' | 'CANCELED' | 'ACTIVE' | 'LOST' | 'CASHED_OUT';


  // Client and host seeds for verification
  server_seed: ServerSeed; // generated by server
  client_seed?: string; // provided by player
  game_seed?: string;
  
  // Board state
  board_state: {
    // Array of 25 cells, each can be 'gem' or 'bomb'
    cell_types: ('gem' | 'bomb')[];
    // Array of revealed cell indices
    revealed_indices: number[];
  };

  completed_at?: Date;

  // Nostr event reference (if published)
  nostr_event_id?: string;

  // mongoose timestamps
  createdAt: Date;
  updatedAt: Date;
}

const MinesGameSchema = new Schema<IMinesGame>(
  {
    player_pubkey: {
      type: String,
      required: false,
      index: true,
    },
    mines_count: {
      type: Number,
      default: 5,
      min: 1,
      max: 24,
    },
    board_state: {
      cell_types: {
        type: [String],
        required: true,
        validate: {
          validator: (arr: string[]) => arr.length === 25,
          message: '5x5 grid must have exactly 25 cells',
        },
      },
      revealed_indices: {
        type: [Number],
        default: [],
      },
    },
    current_multiplier: {
      type: Number,
      default: 1.0,
      min: 1.0,
    },
    wager_amount: {
      type: Number,
      required: true,
      min: 0,
    },
    status: {
      type: String,
      enum: ['WAITING_CLIENT_SEED', 'CANCELED', 'ACTIVE', 'LOST', 'CASHED_OUT'],
      default: 'WAITING_CLIENT_SEED',
    },
    server_seed: {
      type: {
        seed: String,
        hash: String,
      },
      required: true,
    },
    client_seed: String,
    game_seed: String,
    nostr_event_id: String,
    completed_at: Date,
  },
  {
    timestamps: true,
  }
);

// Prevent overwriting the model if it already exists (common in Next.js hot reload)
const MinesGame = mongoose.model<IMinesGame>('MinesGame', MinesGameSchema);

export default MinesGame;
